CREATE DATABASE jobbies;
USE jobbies;

CREATE TABLE jobs (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    title VARCHAR(255),
    body VARCHAR(255),
    applied BOOLEAN DEFAULT NULL,
    -- createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

